# Generated by Django 2.0.5 on 2019-11-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0005_customerservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='service_category',
            field=models.CharField(choices=[('Food', 'Food'), ('Beverages', 'Beverages'), ('Food&Beverages', 'Beverages'), ('MaintenanceCost', 'MaintenanceCost')], default='Food', max_length=10),
        ),
    ]
