# Generated by Django 2.0.5 on 2019-11-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0007_roomstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomstatus',
            old_name='room_status',
            new_name='room_availability',
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='room_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='room_type',
            field=models.CharField(choices=[('Deluxe', 'Deluxe'), ('Executive', 'Executive'), ('Suite', 'Suite')], default=None, max_length=10),
        ),
    ]
