# Generated by Django 2.0.5 on 2019-11-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0010_auto_20191104_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstatus',
            name='room_type',
            field=models.CharField(choices=[('--', '--'), ('Deluxe', 'Deluxe'), ('Executive', 'Executive'), ('Suite', 'Suite')], default=False, max_length=10),
        ),
    ]
