# Generated by Django 2.0.5 on 2019-11-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0011_auto_20191104_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomstatus',
            name='customer_name',
        ),
    ]
