# Generated by Django 2.0.5 on 2019-12-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0014_auto_20191207_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='room_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
