# Generated by Django 2.0.5 on 2019-12-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0015_auto_20191207_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_room_no',
            field=models.IntegerField(default=123, max_length=3),
            preserve_default=False,
        ),
    ]
