# Generated by Django 2.0.5 on 2019-12-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0016_customer_customer_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_room_no',
            field=models.IntegerField(),
        ),
    ]
