# Generated by Django 2.0.5 on 2019-12-08 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0017_auto_20191207_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
