# Generated by Django 2.0.5 on 2019-12-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0018_customer_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='service_consumption_date',
            field=models.DateField(),
        ),
    ]
