# Generated by Django 2.0.5 on 2019-12-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0019_auto_20191207_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='service_consumption_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
