# Generated by Django 2.0.5 on 2019-12-08 02:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0020_auto_20191207_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='service_consumption_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 8, 2, 20, 14, 233266, tzinfo=utc)),
        ),
    ]
