# Generated by Django 2.0.5 on 2019-12-08 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0023_auto_20191208_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_end_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 8, 7, 21, 19, 734770, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_start_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 8, 7, 21, 19, 734748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='service_consumption_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 8, 7, 21, 19, 735239, tzinfo=utc)),
        ),
    ]
