# Generated by Django 2.0.5 on 2019-12-09 21:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0031_auto_20191209_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomstatus',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='roomstatus',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_end_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 9, 21, 32, 6, 367510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_start_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 9, 21, 32, 6, 367473, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='service_consumption_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 9, 21, 32, 6, 368342, tzinfo=utc)),
        ),
    ]
