# Generated by Django 2.0.5 on 2019-12-10 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0032_auto_20191209_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_end_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 8, 28, 222425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_start_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 8, 28, 222401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='service_consumption_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 8, 28, 222921, tzinfo=utc)),
        ),
    ]
