# Generated by Django 2.0.5 on 2019-12-10 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0033_auto_20191210_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_end_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 25, 10, 26529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_start_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 25, 10, 26491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='service_category',
            field=models.CharField(choices=[('Food', 'Food'), ('Beverages', 'Beverages'), ('Food&Beverages', 'Food&Beverages'), ('MaintenanceCost', 'MaintenanceCost')], default='Food', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='service_consumption_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 25, 10, 27290, tzinfo=utc)),
        ),
    ]
