# Generated by Django 2.0.5 on 2019-12-10 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0034_auto_20191210_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_end_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 29, 42, 237876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_start_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 29, 42, 237836, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='service_consumption_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 29, 42, 238720, tzinfo=utc)),
        ),
    ]
