# Generated by Django 2.0.5 on 2019-12-10 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('easymanage', '0035_auto_20191210_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_end_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 30, 27, 701983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_stay_start_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 30, 27, 701960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='service_category',
            field=models.CharField(choices=[('Food', 'Food'), ('Beverages', 'Beverages'), ('Other', 'Other')], default='Food', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='service_consumption_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 6, 30, 27, 702465, tzinfo=utc)),
        ),
    ]
